include: container-image/jobs.gitlab-ci.yml

workflow:
  rules:
  - if: $CI_COMMIT_REF_NAME && $CI_COMMIT_REF_NAME =~ $BRANCH_NAME_PATTERN_QA
    variables:
      CONTAINER_IMAGE_REGISTRY: $CONTAINER_IMAGE_REGISTRY_QA
  - if: $CI_COMMIT_REF_NAME && $CI_COMMIT_REF_NAME =~ $RELEASE_BRANCH_NAME_PATTERN
    variables:
      CONTAINER_IMAGE_REGISTRY: $CONTAINER_IMAGE_REGISTRY_RELEASE
  - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $PRODUCTION_TAG_PATTERN
    variables:
      CONTAINER_IMAGE_REGISTRY: $CONTAINER_IMAGE_REGISTRY_PRODUCTION
  - when: always

build container image:
  extends: .build container image

.build container image:
  extends: .kaniko build container image job
  rules:
  - exists:
    - Dockerfile
