include: container-image/jobs.gitlab-ci.yml

build container image:
  extends: .build container image

.build container image:
  extends: .kaniko build container image job
  rules:
  - exists:
    - Dockerfile
