templates:
  base:
    name: {{ .Values.deploymentReleaseName }}
    namespace: {{ .Values.deploymentNamespace }}
    labels:
      deployment: {{ .Values.deploymentBaseName }}
    values:
    {{- with .Values | getOrNil "image.pullPolicy" }}
    - image:
        pullPolicy: {{ . }}
    {{- end }}
    {{- with .Values | getOrNil "image.registry" }}
    - image:
        registry: {{ . }}
    {{- end }}
    {{- with .Values | getOrNil "ci.annotations" }}
    - podAnnotations:
        {{- . | toYaml | trim | nindent 8 }}
    {{- end }}
    {{- with .Values | getOrNil .Values.deploymentBaseName }}
    - {{- . | toYaml | trim | nindent 6 }}
    {{- end }}
  uses internal alb ingress:
    values:
    {{- $infrastructureAlb := .Values | getOrNil "alb" }}
    {{- $deploymentAlb := .Values | getOrNil .Values.deploymentBaseName | getOrNil "alb" }}
    {{- with $infrastructureAlb | merge $deploymentAlb }}
    {{- if . | getOrNil "enabled" }}
    - ingress:
        annotations:
          {{- with . | getOrNil "certificateArn" }}
          alb.ingress.kubernetes.io/certificate-arn: {{ . }}
          {{- end }}
          {{- with . | getOrNil "groupName" }}
          alb.ingress.kubernetes.io/group.name: {{ . }}
          {{- end }}
          {{- with . | getOrNil "healthcheck.path" }}
          alb.ingress.kubernetes.io/healthcheck-path: {{ . }}
          {{- end }}
          alb.ingress.kubernetes.io/listen-ports: {{
            list (dict "HTTP" 80) (dict "HTTPS" 443) | toJson | quote }}
          alb.ingress.kubernetes.io/scheme: internal
          alb.ingress.kubernetes.io/target-type: ip
        className: alb
        hosts:
        - host: {{
            list
              (list
                ($.Values | getOrNil "hostNamePrefix")
                (list
                  ($.Values | getOrNil (list $.Values.deploymentBaseName "hostNameBase" | join ".")
                    | default $.Values.deploymentName)
                  $.Values.deploymentNamespace
                  | join "-")
                ($.Values | getOrNil "hostNameSuffix")
                | compact
                | join "")
              $.Values.hostDomain
              | join "."
          }}
          paths:
          - path: /
            pathType: Prefix
    {{- end }}
    {{- end }}
