templates:
  base:
    name: {{ .Values.deploymentReleaseName }}
    namespace: {{ .Values.deploymentNamespace }}
    labels:
      deployment: {{ .Values.deploymentBaseName }}
    values:
    {{- with .Values | getOrNil "image.registry" }}
    - image:
        registry: {{ . }}
    {{- end }}
    {{- with .Values | getOrNil "ci.annotations" }}
    - podAnnotations:
        {{- . | toYaml | trim | nindent 8 }}
    {{- end }}
    {{- with .Values | getOrNil .Values.deploymentBaseName }}
    - {{- . | toYaml | trim | nindent 6 }}
    {{- end }}
