include:
- helmfile-jobs.yaml

deploy environment:
  extends: .deploy helmfile job
  tags:
  - $JOB_RUNNER_TAG_DEPLOYMENT
  environment:
    auto_stop_in: $ENVIRONMENT_AUTOSTOP
    name: $ENVIRONMENT_NAME
    on_stop: remove environment

remove environment:
  extends: .destroy helmfile job
  needs:
  - job: deploy environment
  tags: !reference [deploy environment, tags]
  environment:
    name: !reference [deploy environment, environment, name]
