include:
- helmfile-infra/variables.gitlab-ci.yml
- helmfile/jobs.gitlab-ci.yml
- file: teams-notification.yml
  project: devops/gitlab-ci-common

deploy environment:
  extends: .deploy helmfile job
  tags:
  - $JOB_RUNNER_TAG_DEPLOYMENT
  environment:
    auto_stop_in: $ENVIRONMENT_AUTOSTOP
    name: $ENVIRONMENT_NAME
    on_stop: remove environment
  before_script:
  - !reference [.deploy helmfile job, before_script]
  - if [ "$HELMFILE_ENVIRONMENT" == "$ENVIRONMENT_NAME_PRODUCTION" ]; then
  - # When environment is production notify Teams channel about start of deployment
    - !reference [.teams-notification, deploy-start]
  - fi
  after_script:
  - !reference [.deploy helmfile job, after_script]
  - if [ "$HELMFILE_ENVIRONMENT" == "$ENVIRONMENT_NAME_PRODUCTION" ]; then
  - # When environment is production...
    - if [ "$CI_JOB_STATUS" == 'failed' ]; then
    - # When job is failed set deploy result as failure
      - DEPLOY_RESULT=failure
    - else
    - # When job is succeeded set deploy result as success
      - DEPLOY_RESULT=success
    - fi
    - # Notify Teams channel about end of deployment
      - !reference [.teams-notification, deploy-end]
  - fi

remove environment:
  extends: .destroy helmfile job
  needs:
  - job: deploy environment
  tags: !reference [deploy environment, tags]
  environment:
    name: !reference [deploy environment, environment, name]
