include:
- helmfile-infra/variables.gitlab-ci.yml
- helmfile/jobs.gitlab-ci.yml

deploy environment:
  extends: .deploy helmfile job
  tags:
  - $JOB_RUNNER_TAG_DEPLOYMENT
  environment:
    auto_stop_in: $ENVIRONMENT_AUTOSTOP
    name: $ENVIRONMENT_NAME
    on_stop: remove environment
  before_script:
  - !reference [.deploy helmfile job, before_script]
  - if [ "$HELMFILE_ENVIRONMENT" == "$ENVIRONMENT_NAME_PRODUCTION" ]; then
  - # When environment is production...
    - echo Notify Teams Channel about start of deployment
  - fi
  after_script:
  - !reference [.deploy helmfile job, after_script]
  - if [ "$HELMFILE_ENVIRONMENT" == "$ENVIRONMENT_NAME_PRODUCTION" ]; then
  - # When environment is production...
    - if [ "$CI_JOB_STATUS" == 'failed' ]; then
    -
      - DEPLOY_RESULT=failure
    - else
    -
      - DEPLOY_RESULT=success
    - fi
    - echo Notify Teams Channel about deployment $DEPLOY_RESULT
  - fi

remove environment:
  extends: .destroy helmfile job
  needs:
  - job: deploy environment
  tags: !reference [deploy environment, tags]
  environment:
    name: !reference [deploy environment, environment, name]
