include: helm-jobs.yaml

stages:
- test
- build
- publish
- deploy

lint chart:
  extends: .lint chart job
  rules:
  - if: $PIPELINE_CUSTOM_JOBS =~ /^lint chart$/m
    when: never
  - if: $CI_PIPELINE_SOURCE == 'pipeline'
    when: never
  - when: on_success

package chart:
  extends: .package chart job
  rules:
  - if: $PIPELINE_CUSTOM_JOBS =~ /^package chart$/m
    when: never
  - !reference [.package chart job, rules]

publish chart:
  extends: .push chart to artifactory job
  stage: publish

.trigger helmfile infra project job:
  rules:
  - if: >-
      $HELMFILE_ENVIRONMENT
      && $UPSTREAM_ENVIRONMENT_NAME
  stage: deploy
  trigger:
    project: $INFRA_PROJECT_PATH
    strategy: depend
  variables:
    DEPLOYMENT_NAME_SUFFIX: $DEPLOYMENT_NAME_SUFFIX
    HELMFILE_ENVIRONMENT: $HELMFILE_ENVIRONMENT
    UPSTREAM_ENVIRONMENT_AUTOSTOP: $UPSTREAM_ENVIRONMENT_AUTOSTOP
    UPSTREAM_ENVIRONMENT_NAME: $UPSTREAM_ENVIRONMENT_NAME
