include: helm-jobs.yaml

stages:
- test
- build
- pre deploy
- deploy

.trigger helmfile infra project job:
  rules:
  - if: >-
      $HELMFILE_ENVIRONMENT
      && $UPSTREAM_ENVIRONMENT_NAME
  stage: deploy
  trigger:
    project: $INFRA_PROJECT_PATH
    strategy: depend
  variables:
    DEPLOYMENT_NAME_SUFFIX: $DEPLOYMENT_NAME_SUFFIX
    HELMFILE_ENVIRONMENT: $HELMFILE_ENVIRONMENT
    UPSTREAM_ENVIRONMENT_AUTOSTOP: $UPSTREAM_ENVIRONMENT_AUTOSTOP
    UPSTREAM_ENVIRONMENT_NAME: $UPSTREAM_ENVIRONMENT_NAME
