include: helm/jobs.gitlab-ci.yml

stages:
- test
- build
- publish
- deploy

lint chart:
  extends: .lint chart

.lint chart:
  extends: .lint chart job
  rules:
  - if: $CI_PIPELINE_SOURCE == 'pipeline'
    when: never
  - when: on_success
  stage: .pre

package chart:
  extends: .package chart

.package chart:
  extends: .package chart job
  stage: build

publish chart:
  extends: .publish chart

.publish chart:
  extends: .push chart to artifactory job
  stage: publish

deploy environment:
  extends: .deploy environment

.deploy environment:
  rules:
  - if: $CI_PIPELINE_SOURCE != 'pipeline'
    when: never
  - if: >-
      $HELMFILE_ENVIRONMENT
      && $UPSTREAM_ENVIRONMENT_NAME
  stage: deploy
  trigger:
    project: $INFRA_PROJECT_PATH
    strategy: depend
  variables:
    DEPLOYMENT_NAME_SUFFIX: $DEPLOYMENT_NAME_SUFFIX
    HELMFILE_ENVIRONMENT: $HELMFILE_ENVIRONMENT
    UPSTREAM_ENVIRONMENT_AUTOSTOP: $UPSTREAM_ENVIRONMENT_AUTOSTOP
    UPSTREAM_ENVIRONMENT_NAME: $UPSTREAM_ENVIRONMENT_NAME
