include:
- helm/chart-pipeline.gitlab-ci.yml

deploy environment:
  extends: .deploy environment

.deploy environment:
  rules:
  - if: $CI_PIPELINE_SOURCE != 'pipeline'
    when: never
  - if: >-
      $HELMFILE_ENVIRONMENT
      && $UPSTREAM_ENVIRONMENT_NAME
  stage: deploy
  trigger:
    project: $INFRA_PROJECT_PATH
    strategy: depend
  variables:
    CI_LIBRARY_REF_NAME: $CI_LIBRARY_REF_NAME
    DEPLOYMENT_NAME_SUFFIX: $DEPLOYMENT_NAME_SUFFIX
    HELMFILE_ENVIRONMENT: $HELMFILE_ENVIRONMENT
    INFRA_SELECT_DEPLOYMENT: $INFRA_SELECT_DEPLOYMENT
    UPSTREAM_ENVIRONMENT_AUTOSTOP: $UPSTREAM_ENVIRONMENT_AUTOSTOP
    UPSTREAM_ENVIRONMENT_NAME: $UPSTREAM_ENVIRONMENT_NAME
