include: helm-jobs.yaml

stages:
- test
- build
- publish
- deploy

lint chart:
  extends: .lint chart job
  rules:
  - if: $CI_PIPELINE_SOURCE != 'pipeline'

package chart:
  extends: .package chart job

publish chart:
  extends: .push chart to artifactory job
  stage: publish

.trigger helmfile infra project job:
  rules:
  - if: >-
      $HELMFILE_ENVIRONMENT
      && $UPSTREAM_ENVIRONMENT_NAME
  stage: deploy
  trigger:
    project: $INFRA_PROJECT_PATH
    strategy: depend
  variables:
    DEPLOYMENT_NAME_SUFFIX: $DEPLOYMENT_NAME_SUFFIX
    HELMFILE_ENVIRONMENT: $HELMFILE_ENVIRONMENT
    UPSTREAM_ENVIRONMENT_AUTOSTOP: $UPSTREAM_ENVIRONMENT_AUTOSTOP
    UPSTREAM_ENVIRONMENT_NAME: $UPSTREAM_ENVIRONMENT_NAME
