include:
- helmfile-infra/variables.gitlab-ci.yml

variables:
  JOB_RUNNER_TAG_DEPLOYMENT_DEFAULT: gtl-k8s-dev
  JOB_RUNNER_TAG_DEPLOYMENT_PRODUCTION: k8cmd

workflow:
  rules:
  - if: $HELMFILE_ENVIRONMENT == $ENVIRONMENT_NAME_PRODUCTION
    variables:
      JOB_RUNNER_TAG_DEPLOYMENT: $JOB_RUNNER_TAG_DEPLOYMENT_PRODUCTION
  - variables:
      JOB_RUNNER_TAG_DEPLOYMENT: $JOB_RUNNER_TAG_DEPLOYMENT_DEFAULT

environment:
  rules:
  - if: >-
      $CI_PIPELINE_SOURCE == 'pipeline'
      && $HELMFILE_ENVIRONMENT
      && $UPSTREAM_ENVIRONMENT_NAME
  trigger:
    include:
    - file: helmfile-infra/environment-pipeline.gitlab-ci.yml
      project: devops/tools/ci
    strategy: depend
  variables:
    DEPLOYMENT_NAME_SUFFIX: $DEPLOYMENT_NAME_SUFFIX
    ENVIRONMENT_AUTOSTOP: $UPSTREAM_ENVIRONMENT_AUTOSTOP
    ENVIRONMENT_NAME: $UPSTREAM_ENVIRONMENT_NAME
    HELMFILE_ENVIRONMENT: $HELMFILE_ENVIRONMENT
    HELMFILE_ENVS: $HELMFILE_ENVS
