variables:
  ENVIRONMENT_NAME_DEVELOPMENT: dev
  ENVIRONMENT_NAME_PRODUCTION: production
  ENVIRONMENT_NAME_QA: qa
  ENVIRONMENT_NAME_RELEASE: release
  ENVIRONMENT_NAME_STAGING: staging
  ENVIRONMENT_NAME_TESTING: testing
  JIRA_TICKET_PRODUCTION_PATTERN: /^DEPX-[0-9]{3,5}$/
  JOB_RUNNER_TAG_DEPLOYMENT_DEFAULT: gtl-k8s-dev
  JOB_RUNNER_TAG_DEPLOYMENT_PRODUCTION: k8cmd
