include: gitlab/jobs.gitlab-ci.yml

#release-cli create --name "${CI_PROJECT_NAME} Release $CI_COMMIT_BRANCH" --tag-name $CI_COMMIT_BRANCH.$CI_PIPELINE_ID   --description "Deploying release $deploy_tag" --assets-link "{\"name\":\"Change Log\",\"url\":\"https://$GITLAB_URL/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/-/jobs/`cat CI_JOB_ID.txt`/artifacts/file/changelog.log\"}"


create release:
  extends: .get change log job
  script:
  - # Fetch change log
    - !reference [.get change log job, script]
  - # Create release via gitlab api
    - RELEASE_NAME="$RELEASE_PROJECT_NAME release $RELEASE_REF_NAME"
    - >-
      REQUEST_DATA="{
      \"description\": \"Deploying release\",
      \"name\": \"${RELEASE_NAME}\",
      \"ref\": \"${RELEASE_REF_NAME}\",
      \"tag_name\": \"${RELEASE_TAG_NAME}\"
      }"
    - >- # https://docs.gitlab.com/ee/api/releases/#create-a-release | https://curl.se/docs/manpage.html
      curl
      --data "$REQUEST_DATA"
      --fail-with-body
      --header 'Content-Type: application/json'
      --header "PRIVATE-TOKEN: $GITLAB_TOKEN"
      --request POST
      --silent
      ${CI_API_V4_URL}/projects/${RELEASE_PROJECT_ID}/releases
      | jq -r '._links.self // empty'
  variables:
    RELEASE_PROJECT_ID: $CI_PROJECT_ID
    RELEASE_PROJECT_NAME: $CI_PROJECT_NAME
    RELEASE_REF_NAME: $CI_COMMIT_REF_NAME
    RELEASE_TAG_NAME: ${CI_COMMIT_REF_NAME}.${CI_PIPELINE_ID}
