include: gitlab/jobs.gitlab-ci.yml

stages:
- fetch
- apply

get change log:
  stage: fetch
  artifacts:
    paths:
    - "$CHANGELOG_PATH"
  script:
  - mkdir -p $(dirname "$CHANGELOG_PATH")
  - >-
    echo test
    > $CHANGELOG_PATH
  variables:
    CHANGELOG_PATH: logs/changelog.txt

create release:
  stage: apply
  script:
  - ls -la
