include: gitlab/jobs.gitlab-ci.yml

#release-cli create --name "${CI_PROJECT_NAME} Release $CI_COMMIT_BRANCH" --tag-name $CI_COMMIT_BRANCH.$CI_PIPELINE_ID   --description "Deploying release $deploy_tag" --assets-link "{\"name\":\"Change Log\",\"url\":\"https://$GITLAB_URL/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/-/jobs/`cat CI_JOB_ID.txt`/artifacts/file/changelog.log\"}"


create release:
  extends: .get change log job
  script:
  - !reference [.get change log job, script]
  variables:
    GIT_STRATEGY: none
