include: gitlab/jobs.gitlab-ci.yml

stages:
- fetch
- apply

get change log:
  stage: fetch
  artifacts:
    paths:
    - "$CHANGELOG_NAME"
  script:
  - >-
    echo test
    > $CHANGELOG_NAME
  variables:
    CHANGELOG_NAME: changelog

create release:
  stage: apply
  script:
  - ls -la
