.python job:
  image: ${ARTIFACTORY_URL}/dkr/devops-tools-python-job-runner

.pytest job:
  extends: .python job
  stage: test
  script:
  - pytest

.python build job:
  extends: .python job
  stage: build
  artifacts:
    paths:
    - dist
  script:
  - python -m build

.python twine upload job:
  extends: .python job
  stage: deploy
  script:
  - >-
    python -m twine
    upload dist/*
    --non-interactive
  variables:
    TWINE_REPOSITORY_URL: https://artifactory.gtl.net/artifactory/api/pypi/pypi-local
