variables:
  BRANCH_NAME_PATTERN_QA: /^qa$/
  BRANCH_NAME_PATTERN_RELEASE: /^release\/(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*)){2}$/
  PRODUCTION_TAG_PATTERN: /^v(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*)){2}$/
  VERSION_TAG_PATTERN: /^v(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*)){2}($|-[0-9a-zA-Z-]+$)/
